name: Build and push Docker image

env:
  DOCKER_BUILDKIT: 1

inputs:
  ACR_REGISTRY:
    required: true
  ACR_USERNAME:
    required: true
  ACR_PASSWORD:
    required: true

steps:
  - name: Build Docker image
    run: |
      docker build -t finalndbikeoperation .
      docker tag finalndbikeoperation ${{ inputs.ACR_REGISTRY }}/finalndbikeoperation:latest
  - name: Push Docker image to ACR
    run: |
      echo ${{ inputs.ACR_PASSWORD }} | docker login -u ${{ inputs.ACR_USERNAME }} --password-stdin ${{ inputs.ACR_REGISTRY }}
      docker push ${{ inputs.ACR_REGISTRY }}/finalndbikeoperation:latest
