name: Build and push Docker image

on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.2
      - name: Build and push Docker image
        env:
          ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          docker build -t finalndbikeoperation .
          docker tag finalndbikeoperation ${{ env.ACR_REGISTRY }}/finalndbikeoperation:latest
          echo ${{ env.ACR_PASSWORD }} | docker login -u ${{ env.ACR_USERNAME }} --password-stdin ${{ env.ACR_REGISTRY }}
          docker push ${{ env.ACR_REGISTRY }}/finalndbikeoperation:latest
